# Generated by Django 2.0.6 on 2018-06-20 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名')),
                ('description', models.CharField(max_length=500, verbose_name='描述')),
                ('index', models.SmallIntegerField(default=1, verbose_name='分类索引')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('message', models.CharField(max_length=500, verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '联系我',
                'verbose_name_plural': '联系我',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='图片名')),
                ('image', models.ImageField(max_length=200, upload_to='upload/image/', verbose_name='图片url')),
            ],
            options={
                'verbose_name': '图像库',
                'verbose_name_plural': '图像库',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.CharField(max_length=300, verbose_name='描述')),
                ('content', models.TextField(verbose_name='标题内容')),
                ('pub_date', models.DateTimeField(verbose_name='发布日期')),
                ('post_status', models.SmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, verbose_name='文章状态')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击数量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_post', to='post.Category', verbose_name='分类')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_post', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-id'],
            },
        ),
    ]
