# Generated by Django 2.1.3 on 2018-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '留言版',
                'verbose_name_plural': '留言版',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='图片标题')),
                ('image', models.ImageField(max_length=200, upload_to='upload/image/', verbose_name='图片url')),
            ],
            options={
                'verbose_name': '图像库',
                'verbose_name_plural': '图像库',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='MyImage',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-index', '-id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.SmallIntegerField(choices=[(0, '私有'), (1, '公开')], default=0, verbose_name='文章状态'),
        ),
    ]
